
[[http]]
name = "dev-http"
bind-addr = "0.0.0.0:8086"
output = [
    {name="write_1", location = "http://127.0.0.1:5000/write"}
]
query = [
    {name="query_1", location = "http://127.0.0.1:5000/query"}
]
